x= input('Digite algo:')
print('O tipo primitive desse valor é:' ,type(x))
print('So tem espacos?' ,x.isspace())
print('É um numero?',x.isalnum())
print('É maiusculo?' ,x.isalpha())
print('É um digito?' ,x.isdigit())
print('é minusculo',x.islower())
print('é decimal' ,x.isdecimal())
print('é printavel' ,x.isprintable())
